global TABWIDGET
global DALVIKEDIT
global GRAPH
global GRAPH_CALL
global MAINWINDOW
global CONFIG
global APK
global VM
global VMX
global FLAG_JAD
global FLAG_APKTOOL
global NAV_NO
global NAV_P
global FM
global endmethod
global currentclass
global currentmethod
