
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Apr 30 16:34:48 GMT-05:00 2008
//----------------------------------------------------

package jasmin;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 54;
  public static final int INT_KIND = 33;
  public static final int DPARAM_ANNOT_ATTR = 50;
  public static final int DCLASS = 3;
  public static final int STRICTFP = 67;
  public static final int DVAR = 14;
  public static final int DSUPER = 10;
  public static final int DANNOT_ELEM = 47;
  public static final int ENUM = 69;
  public static final int Insn = 78;
  public static final int TABLESWITCH = 71;
  public static final int Int = 79;
  public static final int LOOKUPSWITCH = 70;
  public static final int TRANSIENT = 65;
  public static final int STR_KIND = 45;
  public static final int PROTECTED = 61;
  public static final int ARR_KIND = 41;
  public static final int DARR_ELEM = 46;
  public static final int BOOL_KIND = 37;
  public static final int ANN_KIND = 42;
  public static final int FINAL = 57;
  public static final int DSOURCE = 12;
  public static final int ENUM_KIND = 43;
  public static final int DANNOTATION_ATTR = 31;
  public static final int EQ = 73;
  public static final int LONG_KIND = 38;
  public static final int ABSTRACT = 56;
  public static final int DCLASS_ATTR = 18;
  public static final int DINTERFACE = 16;
  public static final int DFIELD_ATTR = 19;
  public static final int CLS_KIND = 44;
  public static final int NATIVE = 59;
  public static final int DINNER_CLASS_ATTR = 21;
  public static final int DRUNTIME_PARAM_VISIBLE = 29;
  public static final int DTHROWS = 13;
  public static final int INTERFACE = 58;
  public static final int DDEPRECATED = 25;
  public static final int DANNOT_DEFAULT = 49;
  public static final int DSET = 9;
  public static final int DFIELD = 5;
  public static final int DLIMIT = 6;
  public static final int PUBLIC = 62;
  public static final int DRUNTIME_PARAM_INVISIBLE = 30;
  public static final int DNOSUPER = 11;
  public static final int DEND = 4;
  public static final int DMETHOD = 8;
  public static final int DRUNTIME_VISIBLE = 27;
  public static final int DANNOTATION = 32;
  public static final int EOF = 0;
  public static final int DEFAULT = 72;
  public static final int DRUNTIME_INVISIBLE = 28;
  public static final int DENCLOSING_METH = 24;
  public static final int DOUB_KIND = 39;
  public static final int IS = 53;
  public static final int DINNER_CLASS_SPEC_ATTR = 22;
  public static final int METHOD = 55;
  public static final int DSIG_ATTR = 26;
  public static final int error = 1;
  public static final int Word = 77;
  public static final int SYNCHRONIZED = 64;
  public static final int DMETHOD_ATTR = 20;
  public static final int SEP = 74;
  public static final int ANNOTATION = 68;
  public static final int SHORT_KIND = 36;
  public static final int FLOAT_KIND = 40;
  public static final int COLON = 75;
  public static final int USING = 52;
  public static final int DLINE = 7;
  public static final int DCATCH = 2;
  public static final int VOLATILE = 66;
  public static final int CHAR_KIND = 35;
  public static final int DIMPLEMENTS = 15;
  public static final int PRIVATE = 60;
  public static final int TO = 51;
  public static final int STATIC = 63;
  public static final int Str = 76;
  public static final int DCODE_ATTR = 17;
  public static final int Num = 80;
  public static final int BYTE_KIND = 34;
  public static final int DELEM = 48;
  public static final int DSYNTHETIC = 23;
}

